#!/bin/bash

# A shell script to convert a JSON color scheme into a Hyprland configuration file.
# It converts hex colors to their decimal RGB counterparts.
#
# Usage:
#   ./json_to_hyprland.sh <path_to_input.json> > my-colors.conf
#
# Dependencies:
#   - jq: A lightweight and flexible command-line JSON processor.

# --- Script Start ---

# 1. Validate Input
# Check if a file path is provided as the first argument.
# if [ -z "$1" ]; then
#   echo "Usage: $0 <path_to_json_file>" >&2
#   exit 1
# fi
#
# JSON_FILE="$1"

JSON_FILE="$HOME/.local/state/caelestia/scheme.json"

# Check if the provided file actually exists.
if [ ! -f "$JSON_FILE" ]; then
  echo "Error: File not found at '$JSON_FILE'" >&2
  exit 1
fi

# 2. Check for Dependencies
# Ensure 'jq' is installed and available in the system's PATH.
if ! command -v jq &> /dev/null; then
  echo "Error: 'jq' is not installed. Please install it to run this script." >&2
  exit 1
fi

# 3. Generate Header
# Extract metadata from the JSON to create a descriptive header for the config file.
THEME_NAME=$(jq -r '.name' "$JSON_FILE")
THEME_FLAVOUR=$(jq -r '.flavour' "$JSON_FILE")

echo "# -----------------------------------------------------"
echo "# Hyprland colors for theme: $THEME_NAME ($THEME_FLAVOUR)"
echo "# Generated by json_to_hyprland.sh on $(date)"
echo "# -----------------------------------------------------"
echo ""

# 4. Process JSON and Generate RGB value variables
echo "# --- RGB Color Variables ---"
# Use jq to output key-value pairs (e.g., "primary b7c4ff"), then pipe to a while loop.
jq -r '.colours | to_entries[] | "\(.key) \(.value)"' "$JSON_FILE" |
while read -r name hex; do
  # Remove potential '#' from the beginning of the hex code, just in case.
  hex="${hex#\#}"

  # Isolate the R, G, and B hex components using substring extraction.
  r_hex=${hex:0:2}
  g_hex=${hex:2:2}
  b_hex=${hex:4:2}

  # Use bash's built-in arithmetic to convert hex to decimal.
  r_dec=$((16#$r_hex))
  g_dec=$((16#$g_hex))
  b_dec=$((16#$b_hex))

  # Print the final Hyprland variable in the format: $colorName = R G B
  echo "\$$name = $r_dec,$g_dec,$b_dec"
done

